package com.antifraude.drools;

import com.antifraude.drools.RiskContext;
import com.antifraude.drools.fact.TransaccionFact;

global com.antifraude.drools.DroolsService.ScoreTracker scoreTracker;

rule "Fallback - Monto alto"
    salience -100
    when
        $ctx : RiskContext()
        $t : TransaccionFact(monto > 10000) from $ctx.getTransaccionFact()
    then
        scoreTracker.addScore(30);
        System.out.println("[Drools] Fallback - Monto alto: " + $t.getMonto());
end

rule "Fallback - Internacional"
    salience -100
    when
        $ctx : RiskContext()
        $t : TransaccionFact(esInternacional == true) from $ctx.getTransaccionFact()
    then
        scoreTracker.addScore(20);
        System.out.println("[Drools] Fallback - Internacional: " + $t.getPaisOrigenCodigo());
end

rule "Fallback - Horario inhabil"
    salience -100
    when
        $ctx : RiskContext()
        $t : TransaccionFact(fechaTransaccion != null) from $ctx.getTransaccionFact()
        eval($t.getFechaTransaccion().getHour() <= 5 || $t.getFechaTransaccion().getHour() >= 23)
    then
        scoreTracker.addScore(15);
        System.out.println("[Drools] Fallback - Horario inhabil");
end
